[package]
edition = "2021"
name = "tower-rpc"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
background-service = {git = "https://github.com/aschey/background-service-rs", rev = "d76583c5b931ebe6cd52fb077bc513991d24608d"}
bytes = "1"
futures = "0.3"
futures-cancel = {git = "https://github.com/aschey/futures-cancel", rev = "563f413a206c50c7cc1a003cf6a9d3b227b0b04d"}
parity-tokio-ipc = {version = "0.9", optional = true}
serde = {version = "1", features = ["derive"]}
slab = "0.4"
thiserror = "1"
tokio = "1"
tokio-serde = {version = "0.8"}
tokio-stream = {version = "0.1", features = ["sync"]}
tokio-tower = "0.7.0-rc4"
tokio-util = {version = "0.7", features = ["codec"]}
tower = {version = "0.4", features = ["make", "util"]}

[dev-dependencies]
tokio = {version = "1.27.0", features = ["rt-multi-thread", "macros", "time"]}

[features]
bincode = ["tokio-serde/bincode"]
cbor = ["tokio-serde/cbor"]
default = ["bincode", "ipc"]
ipc = ["parity-tokio-ipc"]
json = ["tokio-serde/json"]
messagepack = ["tokio-serde/messagepack"]

[[example]]
name = "pipeline_ipc"
required-features = ["ipc"]

[[example]]
name = "multiplex_ipc"
required-features = ["ipc"]
