[package]
edition = "2021"
name = "tower-rpc"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
background-service = {git = "https://github.com/aschey/background-service-rs", rev = "0d0fc38608bf0443dd9d1ff162f97431248018e3"}
bytes = "1"
futures = "0.3"
futures-cancel = {git = "https://github.com/aschey/futures-cancel", rev = "563f413a206c50c7cc1a003cf6a9d3b227b0b04d"}
parity-tokio-ipc = {version = "0.9", optional = true}
pin-project = "1"
serde = {version = "1", features = ["derive"]}
slab = "0.4"
thiserror = "1"
tokio = {version = "1", features = ["sync", "process"]}
tokio-serde = {version = "0.8"}
tokio-stream = {version = "0.1", features = ["sync"]}
tokio-tower = "0.7.0-rc4"
tokio-util = {version = "0.7", features = ["codec"]}
tower = {version = "0.4", features = ["make", "util"]}

[dev-dependencies]
background-service = {git = "https://github.com/aschey/background-service-rs", rev = "0d0fc38608bf0443dd9d1ff162f97431248018e3", features = ["signal"]}
rand = {version = "0.8.5", features = ["small_rng"]}
tokio = {version = "1.27.0", features = ["rt-multi-thread", "macros", "time", "process"]}
tower = {version = "0.4", features = ["make", "util", "buffer"]}

[features]
bincode = ["tokio-serde/bincode"]
cbor = ["tokio-serde/cbor"]
default = ["bincode", "json", "ipc"]
ipc = ["parity-tokio-ipc"]
json = ["tokio-serde/json"]
messagepack = ["tokio-serde/messagepack"]

[[example]]
name = "ipc_server"
required-features = ["ipc"]
[[example]]
name = "ipc_client"
required-features = ["ipc"]
[[example]]
name = "ipc_multiplex_server"
required-features = ["ipc"]
[[example]]
name = "ipc_multiplex_client"
required-features = ["ipc"]
