[package]
edition = "2021"
name = "tower-rpc"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
background-service = {git = "https://github.com/aschey/background-service-rs", rev = "0d0fc38608bf0443dd9d1ff162f97431248018e3"}
bytes = "1"
futures = "0.3"
futures-cancel = {git = "https://github.com/aschey/futures-cancel", rev = "563f413a206c50c7cc1a003cf6a9d3b227b0b04d"}
matchit = {version = "0.7.0", optional = true}
parity-tokio-ipc = {version = "0.9", optional = true}
pin-project = "1"
serde = {version = "1", features = ["derive"], optional = true}
slab = {version = "0.4", optional = true}
thiserror = "1"
tokio = {version = "1", features = ["sync"]}
tokio-serde = {version = "0.8", optional = true}
tokio-stream = {version = "0.1", features = ["sync"]}
tokio-tower = "0.7.0-rc4"
tokio-util = {version = "0.7", features = ["codec"]}
tower = {version = "0.4", features = ["make", "util"]}
tracing = "0.1"

[dev-dependencies]
background-service = {git = "https://github.com/aschey/background-service-rs", rev = "0d0fc38608bf0443dd9d1ff162f97431248018e3", features = ["signal"]}
criterion = {version = "0.4.0", features = ["async_tokio", "html_reports"]}
rand = {version = "0.8.5", features = ["small_rng"]}
tokio = {version = "1.27.0", features = ["rt-multi-thread", "macros", "time", "process", "net"]}
tower = {version = "0.4", features = ["make", "util", "buffer", "steer", "reconnect"]}
tracing-subscriber = "0.3.17"
tracing-tree2 = {path = "../tracing-tree"}

[features]
bincode = ["serde-codec", "tokio-serde/bincode"]
cbor = ["serde-codec", "tokio-serde/cbor"]
default = ["bincode", "json", "ipc", "tcp", "local", "stdio", "router", "serde-codec", "multiplex"]
ipc = ["parity-tokio-ipc"]
json = ["serde-codec", "tokio-serde/json"]
local = []
messagepack = ["serde-codec", "tokio-serde/messagepack"]
multiplex = ["slab"]
router = ["matchit"]
serde-codec = ["serde", "tokio-serde"]
stdio = ["tokio/process"]
tcp = ["tokio/net"]

[[example]]
name = "ipc_server"
required-features = ["ipc"]
[[example]]
name = "ipc_client"
required-features = ["ipc"]
[[example]]
name = "ipc_multiplex_server"
required-features = ["ipc"]
[[example]]
name = "ipc_multiplex_client"
required-features = ["ipc"]

[[bench]]
harness = false
name = "rpc"
